### ISSUE TITLE
vagrant up --provision  on win 10 64 bit fails

### ISSUE THREAD

**Issue by yarcyarc** [mbertani/lstm-workshop-vm#1]
Win 10 64 bit. Virtualbox 5.1.26. Git 2.14.1. Vagrant 1.9.8. 

mfo@CXPC-76HJQF2 MINGW64 /c/Users/mfo/Documents/git/lstm-workshop-vm (master)
$ vagrant up -provision
D:/winapps/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/plugin/v2/command.rb:59:in `parse_options': ambiguous option: -provision (OptionParser::AmbiguousOption)
        from D:/winapps/vagrant/embedded/gems/gems/vagrant-1.9.8/plugins/commands/up/command.rb:54:in `execute'
        from D:/winapps/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/cli.rb:42:in `execute'
        from D:/winapps/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/environment.rb:308:in `cli'
        from D:/winapps/vagrant/embedded/gems/gems/vagrant-1.9.8/bin/vagrant:138:in `<main>'

--

Am I doing something silly? (I have no experience with vagrant)

**Comment by mbertani** [comment]
Can you try again with `$ vagrant up --provision` ? Seems the double hyphen was lost in the previous command.

**Comment by yarcyarc** [comment]
Silly me. Did the trick.

**Comment by mbertani** [comment]
Great :)
